/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "AreaOfValidity.h"

namespace oai {
namespace amf {
namespace model {

AreaOfValidity::AreaOfValidity() {}

AreaOfValidity::~AreaOfValidity() {}

void AreaOfValidity::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const AreaOfValidity& o) {
  j            = nlohmann::json();
  j["taiList"] = o.m_TaiList;
}

void from_json(const nlohmann::json& j, AreaOfValidity& o) {
  j.at("taiList").get_to(o.m_TaiList);
}

std::vector<Tai>& AreaOfValidity::getTaiList() {
  return m_TaiList;
}

}  // namespace model
}  // namespace amf
}  // namespace oai
