/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ConfiguredSnssai.h"

namespace oai {
namespace amf {
namespace model {

ConfiguredSnssai::ConfiguredSnssai() {
  m_MappedHomeSnssaiIsSet = false;
}

ConfiguredSnssai::~ConfiguredSnssai() {}

void ConfiguredSnssai::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const ConfiguredSnssai& o) {
  j                     = nlohmann::json();
  j["configuredSnssai"] = o.m_ConfiguredSnssai;
  if (o.mappedHomeSnssaiIsSet()) j["mappedHomeSnssai"] = o.m_MappedHomeSnssai;
}

void from_json(const nlohmann::json& j, ConfiguredSnssai& o) {
  j.at("configuredSnssai").get_to(o.m_ConfiguredSnssai);
  if (j.find("mappedHomeSnssai") != j.end()) {
    j.at("mappedHomeSnssai").get_to(o.m_MappedHomeSnssai);
    o.m_MappedHomeSnssaiIsSet = true;
  }
}

Snssai ConfiguredSnssai::getConfiguredSnssai() const {
  return m_ConfiguredSnssai;
}
void ConfiguredSnssai::setConfiguredSnssai(Snssai const& value) {
  m_ConfiguredSnssai = value;
}
Snssai ConfiguredSnssai::getMappedHomeSnssai() const {
  return m_MappedHomeSnssai;
}
void ConfiguredSnssai::setMappedHomeSnssai(Snssai const& value) {
  m_MappedHomeSnssai      = value;
  m_MappedHomeSnssaiIsSet = true;
}
bool ConfiguredSnssai::mappedHomeSnssaiIsSet() const {
  return m_MappedHomeSnssaiIsSet;
}
void ConfiguredSnssai::unsetMappedHomeSnssai() {
  m_MappedHomeSnssaiIsSet = false;
}

}  // namespace model
}  // namespace amf
}  // namespace oai
