/**
 * AMF Communicaiton Service
 * AMF Communication Service
 *
 * OpenAPI spec version: 1.R15.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * N1N2MessageTransferError.h
 *
 *
 */

#ifndef N1N2MessageTransferError_H_
#define N1N2MessageTransferError_H_

//#include "ModelBase.h"

#include "N1N2MsgTxfrErrDetail.h"
#include "ProblemDetails.h"

namespace oai {
namespace amf {
namespace model {

/// <summary>
///
/// </summary>
class N1N2MessageTransferError

{
 public:
  N1N2MessageTransferError();
  virtual ~N1N2MessageTransferError();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate();

  friend void to_json(nlohmann::json& j, const N1N2MessageTransferError& o);
  friend void from_json(const nlohmann::json& j, N1N2MessageTransferError& o);

  /////////////////////////////////////////////
  /// N1N2MessageTransferError members

  /// <summary>
  ///
  /// </summary>
  ProblemDetails getError() const;
  void setError(ProblemDetails const& value);
  /// <summary>
  ///
  /// </summary>
  N1N2MsgTxfrErrDetail getErrInfo() const;
  void setErrInfo(N1N2MsgTxfrErrDetail const& value);
  bool errInfoIsSet() const;
  void unsetErrInfo();

 protected:
  ProblemDetails m_Error;

  N1N2MsgTxfrErrDetail m_ErrInfo;
  bool m_ErrInfoIsSet;
};

}  // namespace model
}  // namespace amf
}  // namespace oai

#endif /* N1N2MessageTransferError_H_ */
