/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "N1N2MsgTxfrErrDetail.h"

namespace oai {
namespace amf {
namespace model {

N1N2MsgTxfrErrDetail::N1N2MsgTxfrErrDetail() {
  m_RetryAfter          = 0;
  m_RetryAfterIsSet     = false;
  m_HighestPrioArpIsSet = false;
}

N1N2MsgTxfrErrDetail::~N1N2MsgTxfrErrDetail() {}

void N1N2MsgTxfrErrDetail::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const N1N2MsgTxfrErrDetail& o) {
  j = nlohmann::json();
  if (o.retryAfterIsSet()) j["retryAfter"] = o.m_RetryAfter;
  if (o.highestPrioArpIsSet()) j["highestPrioArp"] = o.m_HighestPrioArp;
}

void from_json(const nlohmann::json& j, N1N2MsgTxfrErrDetail& o) {
  if (j.find("retryAfter") != j.end()) {
    j.at("retryAfter").get_to(o.m_RetryAfter);
    o.m_RetryAfterIsSet = true;
  }
  if (j.find("highestPrioArp") != j.end()) {
    j.at("highestPrioArp").get_to(o.m_HighestPrioArp);
    o.m_HighestPrioArpIsSet = true;
  }
}

int32_t N1N2MsgTxfrErrDetail::getRetryAfter() const {
  return m_RetryAfter;
}
void N1N2MsgTxfrErrDetail::setRetryAfter(int32_t const value) {
  m_RetryAfter      = value;
  m_RetryAfterIsSet = true;
}
bool N1N2MsgTxfrErrDetail::retryAfterIsSet() const {
  return m_RetryAfterIsSet;
}
void N1N2MsgTxfrErrDetail::unsetRetryAfter() {
  m_RetryAfterIsSet = false;
}
Arp N1N2MsgTxfrErrDetail::getHighestPrioArp() const {
  return m_HighestPrioArp;
}
void N1N2MsgTxfrErrDetail::setHighestPrioArp(Arp const& value) {
  m_HighestPrioArp      = value;
  m_HighestPrioArpIsSet = true;
}
bool N1N2MsgTxfrErrDetail::highestPrioArpIsSet() const {
  return m_HighestPrioArpIsSet;
}
void N1N2MsgTxfrErrDetail::unsetHighestPrioArp() {
  m_HighestPrioArpIsSet = false;
}

}  // namespace model
}  // namespace amf
}  // namespace oai
