/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * N2InformationTransferError.h
 *
 *
 */

#ifndef N2InformationTransferError_H_
#define N2InformationTransferError_H_

#include "ProblemDetails_2.h"
#include "PWSErrorData.h"
#include <nlohmann/json.hpp>

namespace oai {
namespace amf {
namespace model {

/// <summary>
///
/// </summary>
class N2InformationTransferError {
 public:
  N2InformationTransferError();
  virtual ~N2InformationTransferError();

  void validate();

  /////////////////////////////////////////////
  /// N2InformationTransferError members

  /// <summary>
  ///
  /// </summary>
  ProblemDetails_2 getError() const;
  void setError(ProblemDetails_2 const& value);
  /// <summary>
  ///
  /// </summary>
  PWSErrorData getPwdErrorInfo() const;
  void setPwdErrorInfo(PWSErrorData const& value);
  bool pwdErrorInfoIsSet() const;
  void unsetPwdErrorInfo();

  friend void to_json(nlohmann::json& j, const N2InformationTransferError& o);
  friend void from_json(const nlohmann::json& j, N2InformationTransferError& o);

 protected:
  ProblemDetails_2 m_Error;

  PWSErrorData m_PwdErrorInfo;
  bool m_PwdErrorInfoIsSet;
};

}  // namespace model
}  // namespace amf
}  // namespace oai

#endif /* N2InformationTransferError_H_ */
