/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NasSecurityMode.h
 *
 *
 */

#ifndef NasSecurityMode_H_
#define NasSecurityMode_H_

#include "IntegrityAlgorithm.h"
#include "CipheringAlgorithm.h"
#include <nlohmann/json.hpp>

namespace oai {
namespace amf {
namespace model {

/// <summary>
///
/// </summary>
class NasSecurityMode {
 public:
  NasSecurityMode();
  virtual ~NasSecurityMode();

  void validate();

  /////////////////////////////////////////////
  /// NasSecurityMode members

  /// <summary>
  ///
  /// </summary>
  IntegrityAlgorithm getIntegrityAlgorithm() const;
  void setIntegrityAlgorithm(IntegrityAlgorithm const& value);
  /// <summary>
  ///
  /// </summary>
  CipheringAlgorithm getCipheringAlgorithm() const;
  void setCipheringAlgorithm(CipheringAlgorithm const& value);

  friend void to_json(nlohmann::json& j, const NasSecurityMode& o);
  friend void from_json(const nlohmann::json& j, NasSecurityMode& o);

 protected:
  IntegrityAlgorithm m_IntegrityAlgorithm;

  CipheringAlgorithm m_CipheringAlgorithm;
};

}  // namespace model
}  // namespace amf
}  // namespace oai

#endif /* NasSecurityMode_H_ */
