/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PWSErrorData.h"

namespace oai {
namespace amf {
namespace model {

PWSErrorData::PWSErrorData() {
  m_NamfCause = 0;
}

PWSErrorData::~PWSErrorData() {}

void PWSErrorData::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const PWSErrorData& o) {
  j              = nlohmann::json();
  j["namfCause"] = o.m_NamfCause;
}

void from_json(const nlohmann::json& j, PWSErrorData& o) {
  j.at("namfCause").get_to(o.m_NamfCause);
}

int32_t PWSErrorData::getNamfCause() const {
  return m_NamfCause;
}
void PWSErrorData::setNamfCause(int32_t const value) {
  m_NamfCause = value;
}

}  // namespace model
}  // namespace amf
}  // namespace oai
