/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "UeRegStatusUpdateReqData.h"

namespace oai {
namespace amf {
namespace model {

UeRegStatusUpdateReqData::UeRegStatusUpdateReqData() {
  m_ToReleaseSessionListIsSet = false;
  m_PcfReselectedInd          = false;
  m_PcfReselectedIndIsSet     = false;
}

UeRegStatusUpdateReqData::~UeRegStatusUpdateReqData() {}

void UeRegStatusUpdateReqData::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const UeRegStatusUpdateReqData& o) {
  j                   = nlohmann::json();
  j["transferStatus"] = o.m_TransferStatus;
  if (o.toReleaseSessionListIsSet())
    j["toReleaseSessionList"] = o.m_ToReleaseSessionList;
  if (o.pcfReselectedIndIsSet()) j["pcfReselectedInd"] = o.m_PcfReselectedInd;
}

void from_json(const nlohmann::json& j, UeRegStatusUpdateReqData& o) {
  j.at("transferStatus").get_to(o.m_TransferStatus);
  if (j.find("toReleaseSessionList") != j.end()) {
    j.at("toReleaseSessionList").get_to(o.m_ToReleaseSessionList);
    o.m_ToReleaseSessionListIsSet = true;
  }
  if (j.find("pcfReselectedInd") != j.end()) {
    j.at("pcfReselectedInd").get_to(o.m_PcfReselectedInd);
    o.m_PcfReselectedIndIsSet = true;
  }
}

UeContextTransferStatus UeRegStatusUpdateReqData::getTransferStatus() const {
  return m_TransferStatus;
}
void UeRegStatusUpdateReqData::setTransferStatus(
    UeContextTransferStatus const& value) {
  m_TransferStatus = value;
}
std::vector<int32_t>& UeRegStatusUpdateReqData::getToReleaseSessionList() {
  return m_ToReleaseSessionList;
}
bool UeRegStatusUpdateReqData::toReleaseSessionListIsSet() const {
  return m_ToReleaseSessionListIsSet;
}
void UeRegStatusUpdateReqData::unsetToReleaseSessionList() {
  m_ToReleaseSessionListIsSet = false;
}
bool UeRegStatusUpdateReqData::isPcfReselectedInd() const {
  return m_PcfReselectedInd;
}
void UeRegStatusUpdateReqData::setPcfReselectedInd(bool const value) {
  m_PcfReselectedInd      = value;
  m_PcfReselectedIndIsSet = true;
}
bool UeRegStatusUpdateReqData::pcfReselectedIndIsSet() const {
  return m_PcfReselectedIndIsSet;
}
void UeRegStatusUpdateReqData::unsetPcfReselectedInd() {
  m_PcfReselectedIndIsSet = false;
}

}  // namespace model
}  // namespace amf
}  // namespace oai
