apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-nr-ue.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if  contains "ClusterIP" .Values.service.type }}
  clusterIP: None
{{- end }}
  ports:
    - name: s1c
      port: {{ .Values.service.s1cPort }}
      targetPort: {{ .Values.service.s1cPort }}
      protocol: UDP
    - name: s1u
      port: {{ .Values.service.s1uPort }}
      targetPort: {{ .Values.service.s1uPort }}
      protocol: UDP
    - name: x2c
      port: {{ .Values.service.x2cPort }}
      targetPort: {{ .Values.service.x2cPort }}
      protocol: UDP
  selector:
    {{- include "oai-nr-ue.selectorLabels" . | nindent 4 }}
