/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MmeCapabilities.h
 *
 *
 */

#ifndef OAI_SMF_MODEL_MmeCapabilities_H_
#define OAI_SMF_MODEL_MmeCapabilities_H_

#include "../ModelBase.h"

namespace oai {
namespace smf {
namespace model {

/// <summary>
///
/// </summary>
class MmeCapabilities : public ModelBase {
 public:
  MmeCapabilities();
  virtual ~MmeCapabilities();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  void fromJson(const web::json::value& json) override;

  void toMultipart(
      std::shared_ptr<MultipartFormData> multipart,
      const utility::string_t& namePrefix) const override;
  void fromMultiPart(
      std::shared_ptr<MultipartFormData> multipart,
      const utility::string_t& namePrefix) override;

  /////////////////////////////////////////////
  /// MmeCapabilities members

  /// <summary>
  ///
  /// </summary>
  bool isNonIpSupported() const;
  bool nonIpSupportedIsSet() const;
  void unsetNonIpSupported();

  void setNonIpSupported(bool value);

 protected:
  bool m_NonIpSupported;
  bool m_NonIpSupportedIsSet;
};

}  // namespace model
}  // namespace smf
}  // namespace oai

#endif /* OAI_SMF_MODEL_MmeCapabilities_H_ */
