/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TraceData.h
 *
 *
 */

#ifndef OAI_SMF_MODEL_TraceData_H_
#define OAI_SMF_MODEL_TraceData_H_

#include "../ModelBase.h"

#include "TraceDepth.h"
#include <cpprest/details/basic_types.h>

namespace oai {
namespace smf {
namespace model {

/// <summary>
///
/// </summary>
class TraceData : public ModelBase {
 public:
  TraceData();
  virtual ~TraceData();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  void fromJson(const web::json::value& json) override;

  void toMultipart(
      std::shared_ptr<MultipartFormData> multipart,
      const utility::string_t& namePrefix) const override;
  void fromMultiPart(
      std::shared_ptr<MultipartFormData> multipart,
      const utility::string_t& namePrefix) override;

  /////////////////////////////////////////////
  /// TraceData members

  /// <summary>
  ///
  /// </summary>
  utility::string_t getTraceRef() const;

  void setTraceRef(const utility::string_t& value);

  /// <summary>
  ///
  /// </summary>
  std::shared_ptr<TraceDepth> getTraceDepth() const;

  void setTraceDepth(const std::shared_ptr<TraceDepth>& value);

  /// <summary>
  ///
  /// </summary>
  utility::string_t getNeTypeList() const;

  void setNeTypeList(const utility::string_t& value);

  /// <summary>
  ///
  /// </summary>
  utility::string_t getEventList() const;

  void setEventList(const utility::string_t& value);

  /// <summary>
  ///
  /// </summary>
  utility::string_t getCollectionEntityIpv4Addr() const;
  bool collectionEntityIpv4AddrIsSet() const;
  void unsetCollectionEntityIpv4Addr();

  void setCollectionEntityIpv4Addr(const utility::string_t& value);

  /// <summary>
  ///
  /// </summary>
  utility::string_t getCollectionEntityIpv6Addr() const;
  bool collectionEntityIpv6AddrIsSet() const;
  void unsetCollectionEntityIpv6Addr();

  void setCollectionEntityIpv6Addr(const utility::string_t& value);

  /// <summary>
  ///
  /// </summary>
  utility::string_t getInterfaceList() const;
  bool interfaceListIsSet() const;
  void unsetInterfaceList();

  void setInterfaceList(const utility::string_t& value);

 protected:
  utility::string_t m_TraceRef;
  std::shared_ptr<TraceDepth> m_TraceDepth;
  utility::string_t m_NeTypeList;
  utility::string_t m_EventList;
  utility::string_t m_CollectionEntityIpv4Addr;
  bool m_CollectionEntityIpv4AddrIsSet;
  utility::string_t m_CollectionEntityIpv6Addr;
  bool m_CollectionEntityIpv6AddrIsSet;
  utility::string_t m_InterfaceList;
  bool m_InterfaceListIsSet;
};

}  // namespace model
}  // namespace smf
}  // namespace oai

#endif /* OAI_SMF_MODEL_TraceData_H_ */
