/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UserLocation.h
 *
 *
 */

#ifndef OAI_SMF_MODEL_UserLocation_H_
#define OAI_SMF_MODEL_UserLocation_H_

#include "../ModelBase.h"

#include "EutraLocation.h"
#include "NrLocation.h"
#include "N3gaLocation.h"

namespace oai {
namespace smf {
namespace model {

/// <summary>
///
/// </summary>
class UserLocation : public ModelBase {
 public:
  UserLocation();
  virtual ~UserLocation();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  void fromJson(const web::json::value& json) override;

  void toMultipart(
      std::shared_ptr<MultipartFormData> multipart,
      const utility::string_t& namePrefix) const override;
  void fromMultiPart(
      std::shared_ptr<MultipartFormData> multipart,
      const utility::string_t& namePrefix) override;

  /////////////////////////////////////////////
  /// UserLocation members

  /// <summary>
  ///
  /// </summary>
  std::shared_ptr<EutraLocation> getEutraLocation() const;
  bool eutraLocationIsSet() const;
  void unsetEutraLocation();

  void setEutraLocation(const std::shared_ptr<EutraLocation>& value);

  /// <summary>
  ///
  /// </summary>
  std::shared_ptr<NrLocation> getNrLocation() const;
  bool nrLocationIsSet() const;
  void unsetNrLocation();

  void setNrLocation(const std::shared_ptr<NrLocation>& value);

  /// <summary>
  ///
  /// </summary>
  std::shared_ptr<N3gaLocation> getN3gaLocation() const;
  bool n3gaLocationIsSet() const;
  void unsetN3gaLocation();

  void setN3gaLocation(const std::shared_ptr<N3gaLocation>& value);

 protected:
  std::shared_ptr<EutraLocation> m_EutraLocation;
  bool m_EutraLocationIsSet;
  std::shared_ptr<NrLocation> m_NrLocation;
  bool m_NrLocationIsSet;
  std::shared_ptr<N3gaLocation> m_N3gaLocation;
  bool m_N3gaLocationIsSet;
};

}  // namespace model
}  // namespace smf
}  // namespace oai

#endif /* OAI_SMF_MODEL_UserLocation_H_ */
