/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MultipartFormData.h
 *
 * This class represents a container for building
 * application/x-multipart-formdata requests.
 */

#ifndef OAI_SMF_MODEL_MultipartFormData_H_
#define OAI_SMF_MODEL_MultipartFormData_H_

#include "IHttpBody.h"
#include "HttpContent.h"

#include <vector>
#include <map>
#include <memory>

#include <cpprest/details/basic_types.h>

namespace oai {
namespace smf {
namespace model {

class MultipartFormData : public IHttpBody {
 public:
  MultipartFormData();
  MultipartFormData(const utility::string_t& boundary);
  virtual ~MultipartFormData();

  virtual void add(std::shared_ptr<HttpContent> content);
  virtual utility::string_t getBoundary();
  virtual std::shared_ptr<HttpContent> getContent(
      const utility::string_t& name) const;
  virtual bool hasContent(const utility::string_t& name) const;
  virtual void writeTo(std::ostream& target);

 protected:
  std::vector<std::shared_ptr<HttpContent>> m_Contents;
  utility::string_t m_Boundary;
  std::map<utility::string_t, std::shared_ptr<HttpContent>> m_ContentLookup;
};

}  // namespace model
}  // namespace smf
}  // namespace oai

#endif /* OAI_SMF_MODEL_MultipartFormData_H_ */
