/**
 * NRF NFManagement Service
 * NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Ipv6PrefixRange.h
 *
 *
 */

#ifndef Ipv6PrefixRange_H_
#define Ipv6PrefixRange_H_

#include "Ipv6Prefix.h"
#include <nlohmann/json.hpp>

namespace oai {
namespace nrf {
namespace model {

/// <summary>
///
/// </summary>
class Ipv6PrefixRange {
 public:
  Ipv6PrefixRange();
  virtual ~Ipv6PrefixRange();

  void validate();

  /////////////////////////////////////////////
  /// Ipv6PrefixRange members

  /// <summary>
  ///
  /// </summary>
  Ipv6Prefix getStart() const;
  void setStart(Ipv6Prefix const& value);
  bool startIsSet() const;
  void unsetStart();
  /// <summary>
  ///
  /// </summary>
  Ipv6Prefix getEnd() const;
  void setEnd(Ipv6Prefix const& value);
  bool endIsSet() const;
  void unsetEnd();

  friend void to_json(nlohmann::json& j, const Ipv6PrefixRange& o);
  friend void from_json(const nlohmann::json& j, Ipv6PrefixRange& o);

 protected:
  Ipv6Prefix m_Start;
  bool m_StartIsSet;
  Ipv6Prefix m_End;
  bool m_EndIsSet;
};

}  // namespace model
}  // namespace nrf
}  // namespace oai

#endif /* Ipv6PrefixRange_H_ */
