/**
 * NRF NFManagement Service
 * NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NetworkSliceCond.h
 *
 *
 */

#ifndef NetworkSliceCond_H_
#define NetworkSliceCond_H_

#include <string>
#include "Snssai.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai {
namespace nrf {
namespace model {

/// <summary>
///
/// </summary>
class NetworkSliceCond {
 public:
  NetworkSliceCond();
  virtual ~NetworkSliceCond();

  void validate();

  /////////////////////////////////////////////
  /// NetworkSliceCond members

  /// <summary>
  ///
  /// </summary>
  std::vector<Snssai>& getSnssaiList();
  void setSnssaiList(std::vector<Snssai> const& value);
  /// <summary>
  ///
  /// </summary>
  std::vector<std::string>& getNsiList();
  void setNsiList(std::vector<std::string> const& value);
  bool nsiListIsSet() const;
  void unsetNsiList();

  friend void to_json(nlohmann::json& j, const NetworkSliceCond& o);
  friend void from_json(const nlohmann::json& j, NetworkSliceCond& o);

 protected:
  std::vector<Snssai> m_SnssaiList;

  std::vector<std::string> m_NsiList;
  bool m_NsiListIsSet;
};

}  // namespace model
}  // namespace nrf
}  // namespace oai

#endif /* NetworkSliceCond_H_ */
