/**
 * NRF NFManagement Service
 * NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ServiceName.h"

namespace oai {
namespace nrf {
namespace model {

ServiceName::ServiceName() {}

ServiceName::~ServiceName() {}

void ServiceName::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const ServiceName& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, ServiceName& o) {}

}  // namespace model
}  // namespace nrf
}  // namespace oai
