/**
 * NRF NFDiscovery Service
 * NRF NFDiscovery Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * StoredSearchResult.h
 *
 *
 */

#ifndef StoredSearchResult_H_
#define StoredSearchResult_H_

#include "NFProfile.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai {
namespace nrf {
namespace model {

/// <summary>
///
/// </summary>
class StoredSearchResult {
 public:
  StoredSearchResult();
  virtual ~StoredSearchResult();

  void validate();

  /////////////////////////////////////////////
  /// StoredSearchResult members

  /// <summary>
  ///
  /// </summary>
  std::vector<NFProfile>& getNfInstances();
  void setNfInstances(std::vector<NFProfile> const& value);

  friend void to_json(nlohmann::json& j, const StoredSearchResult& o);
  friend void from_json(const nlohmann::json& j, StoredSearchResult& o);

 protected:
  std::vector<NFProfile> m_NfInstances;
};

}  // namespace model
}  // namespace nrf
}  // namespace oai

#endif /* StoredSearchResult_H_ */
