/**
 * NRF NFManagement Service
 * NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "TransportProtocol.h"

namespace oai {
namespace nrf {
namespace model {

TransportProtocol::TransportProtocol() {}

TransportProtocol::~TransportProtocol() {}

void TransportProtocol::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const TransportProtocol& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, TransportProtocol& o) {}

}  // namespace model
}  // namespace nrf
}  // namespace oai
