---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-{{ .Values.namespace }}-net1
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens3",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.nausfIPmain "/" .Values.multus.nausfIPnetmask | nospace | quote }},
                        "gateway": {{- cat .Values.multus.nausfIPGw | quote }}
                }
        ]
      }
    }'
