/**
 * Nsmf_EventExposure
 * Session Management Event Exposure Service. © 2019, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * DddStatus.h
 *
 * Possible values are - BUFFERED: The downlink data are buffered. -
 * TRANSMITTED: The downlink data are transmitted - DISCARDED: The downlink data
 * are discarded.
 */

#ifndef DddStatus_H_
#define DddStatus_H_

#include <nlohmann/json.hpp>

namespace oai {
namespace smf_server {
namespace model {

/// <summary>
/// Possible values are - BUFFERED: The downlink data are buffered. -
/// TRANSMITTED: The downlink data are transmitted - DISCARDED: The downlink
/// data are discarded.
/// </summary>
class DddStatus {
 public:
  DddStatus();
  virtual ~DddStatus();

  void validate();

  /////////////////////////////////////////////
  /// DddStatus members

  friend void to_json(nlohmann::json& j, const DddStatus& o);
  friend void from_json(const nlohmann::json& j, DddStatus& o);

 protected:
};

}  // namespace model
}  // namespace smf_server
}  // namespace oai

#endif /* DddStatus_H_ */
