/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "EpsBearerInfo.h"

namespace oai {
namespace smf_server {
namespace model {

EpsBearerInfo::EpsBearerInfo() {
  m_Ebi = 0;
}

EpsBearerInfo::~EpsBearerInfo() {}

void EpsBearerInfo::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const EpsBearerInfo& o) {
  j                   = nlohmann::json();
  j["ebi"]            = o.m_Ebi;
  j["pgwS8uFteid"]    = o.m_PgwS8uFteid;
  j["bearerLevelQoS"] = o.m_BearerLevelQoS;
}

void from_json(const nlohmann::json& j, EpsBearerInfo& o) {
  j.at("ebi").get_to(o.m_Ebi);
  j.at("pgwS8uFteid").get_to(o.m_PgwS8uFteid);
  j.at("bearerLevelQoS").get_to(o.m_BearerLevelQoS);
}

int32_t EpsBearerInfo::getEbi() const {
  return m_Ebi;
}
void EpsBearerInfo::setEbi(int32_t const value) {
  m_Ebi = value;
}
std::string EpsBearerInfo::getPgwS8uFteid() const {
  return m_PgwS8uFteid;
}
void EpsBearerInfo::setPgwS8uFteid(std::string const& value) {
  m_PgwS8uFteid = value;
}
std::string EpsBearerInfo::getBearerLevelQoS() const {
  return m_BearerLevelQoS;
}
void EpsBearerInfo::setBearerLevelQoS(std::string const& value) {
  m_BearerLevelQoS = value;
}

}  // namespace model
}  // namespace smf_server
}  // namespace oai
