/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * QosFlowNotifyItem.h
 *
 *
 */

#ifndef QosFlowNotifyItem_H_
#define QosFlowNotifyItem_H_

#include "NotificationCause.h"
#include <nlohmann/json.hpp>

namespace oai {
namespace smf_server {
namespace model {

/// <summary>
///
/// </summary>
class QosFlowNotifyItem {
 public:
  QosFlowNotifyItem();
  virtual ~QosFlowNotifyItem();

  void validate();

  /////////////////////////////////////////////
  /// QosFlowNotifyItem members

  /// <summary>
  ///
  /// </summary>
  int32_t getQfi() const;
  void setQfi(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  NotificationCause getNotificationCause() const;
  void setNotificationCause(NotificationCause const& value);

  friend void to_json(nlohmann::json& j, const QosFlowNotifyItem& o);
  friend void from_json(const nlohmann::json& j, QosFlowNotifyItem& o);

 protected:
  int32_t m_Qfi;

  NotificationCause m_NotificationCause;
};

}  // namespace model
}  // namespace smf_server
}  // namespace oai

#endif /* QosFlowNotifyItem_H_ */
