/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * QosFlowItem.h
 *
 *
 */

#ifndef QosFlowItem_H_
#define QosFlowItem_H_

#include "Cause.h"
#include <nlohmann/json.hpp>

namespace oai {
namespace smf_server {
namespace model {

/// <summary>
///
/// </summary>
class QosFlowItem {
 public:
  QosFlowItem();
  virtual ~QosFlowItem();

  void validate();

  /////////////////////////////////////////////
  /// QosFlowItem members

  /// <summary>
  ///
  /// </summary>
  int32_t getQfi() const;
  void setQfi(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  Cause getCause() const;
  void setCause(Cause const& value);
  bool causeIsSet() const;
  void unsetCause();

  friend void to_json(nlohmann::json& j, const QosFlowItem& o);
  friend void from_json(const nlohmann::json& j, QosFlowItem& o);

 protected:
  int32_t m_Qfi;

  Cause m_Cause;
  bool m_CauseIsSet;
};

}  // namespace model
}  // namespace smf_server
}  // namespace oai

#endif /* QosFlowItem_H_ */
