/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SmContextType.h
 *
 * Possible values are   - EPS_PDN_CONNECTION   - SM_CONTEXT
 */

#ifndef SmContextType_H_
#define SmContextType_H_

#include <nlohmann/json.hpp>

namespace oai {
namespace smf_server {
namespace model {

/// <summary>
/// Possible values are   - EPS_PDN_CONNECTION   - SM_CONTEXT
/// </summary>
class SmContextType {
 public:
  SmContextType();
  virtual ~SmContextType();

  void validate();

  /////////////////////////////////////////////
  /// SmContextType members

  friend void to_json(nlohmann::json& j, const SmContextType& o);
  friend void from_json(const nlohmann::json& j, SmContextType& o);

 protected:
};

}  // namespace model
}  // namespace smf_server
}  // namespace oai

#endif /* SmContextType_H_ */
