/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Snssai.h
 *
 *
 */

#ifndef Snssai_H_
#define Snssai_H_

#include <string>
#include <nlohmann/json.hpp>

namespace oai {
namespace smf_server {
namespace model {

/// <summary>
///
/// </summary>
class Snssai {
 public:
  Snssai();
  Snssai(uint8_t sst, std::string sd) : m_Sst(sst), m_Sd(sd) {
    m_SdIsSet = true;
  };
  virtual ~Snssai();

  void validate();

  /////////////////////////////////////////////
  /// Snssai members

  /// <summary>
  ///
  /// </summary>
  uint8_t getSst() const;
  void setSst(uint8_t const value);
  /// <summary>
  ///
  /// </summary>
  // uint32_t getSd() const;
  // void setSd(uint32_t const& value);
  std::string getSd() const;
  void setSd(std::string const& value);
  bool sdIsSet() const;
  void unsetSd();

  friend void to_json(nlohmann::json& j, const Snssai& o);
  friend void from_json(const nlohmann::json& j, Snssai& o);

 protected:
  uint8_t m_Sst;

  std::string m_Sd;
  // uint32_t m_Sd:24;
  bool m_SdIsSet;
};

}  // namespace model
}  // namespace smf_server
}  // namespace oai

#endif /* Snssai_H_ */
