/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "StatusNotification.h"

namespace oai {
namespace smf_server {
namespace model {

StatusNotification::StatusNotification() {}

StatusNotification::~StatusNotification() {}

void StatusNotification::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const StatusNotification& o) {
  j               = nlohmann::json();
  j["statusInfo"] = o.m_StatusInfo;
}

void from_json(const nlohmann::json& j, StatusNotification& o) {
  j.at("statusInfo").get_to(o.m_StatusInfo);
}

StatusInfo StatusNotification::getStatusInfo() const {
  return m_StatusInfo;
}
void StatusNotification::setStatusInfo(StatusInfo const& value) {
  m_StatusInfo = value;
}

}  // namespace model
}  // namespace smf_server
}  // namespace oai
