/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * N1N2IndividualSubscriptionDocumentApiImpl.h
 *
 *
 */

#ifndef N1_N2_INDIVIDUAL_SUBSCRIPTION_DOCUMENT_API_IMPL_H_
#define N1_N2_INDIVIDUAL_SUBSCRIPTION_DOCUMENT_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <N1N2IndividualSubscriptionDocumentApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
#include <string>

#include "amf_app.hpp"

namespace oai {
namespace amf {
namespace api {

class N1N2IndividualSubscriptionDocumentApiImpl
    : public oai::amf::api::N1N2IndividualSubscriptionDocumentApi {
 public:
  N1N2IndividualSubscriptionDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>,
      amf_application::amf_app* amf_app_inst);
  ~N1N2IndividualSubscriptionDocumentApiImpl() {}

  void n1_n2_message_un_subscribe(
      const std::string& ueContextId, const std::string& subscriptionId,
      Pistache::Http::ResponseWriter& response);

 private:
  amf_application::amf_app* m_amf_app;
};

}  // namespace api
}  // namespace amf
}  // namespace oai

#endif
